name: test
on: [push, pull_request]
jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        WITH_LOGGING: [0, 1]
        WITH_DESTRUCTIVE_COMMANDS: [0, 1]
    steps:
        - run: sudo apt-get update
        - run: sudo apt-get install -y gcc-arm-none-eabi cmake
        - uses: actions/checkout@v4
        - run: cmake -DPICO_SDK_FETCH_FROM_GIT=1 -DWITH_LOGGING=${{ matrix.WITH_LOGGING }} -DWITH_DESTRUCTIVE_CMDS=${{ matrix.WITH_DESTRUCTIVE_COMMANDS }} -S . -B build
        - run: cmake --build build/
